# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5d566e950c2a037a89e8934bfbebb79f4070d5f594a3e9086816ff468fc16236cdf77999127e15a7b33e7a217b5a536396362393889405a56d10264f1ff183c

test:
  secret_key_base: 7712e6474442383fb5270bb1a3c09990a9b52c6afcc0cbd76b19eb9ef4648eaca191457ab6794cf048ed451675a906689a2ce30b2f97f8baa1c51368fc448077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
